# 自分で作成したZoomアプリのものに変える
ZOOM_CLIENT_ID          :=
ZOOM_CLIENT_SECRET      :=
# 自分でngrokで用意したURLに変える
ZOOM_OAUTH_REDIRECT_URI :=REPLACE_ME

run_example:
	go run main.go -zoomClientID=$(ZOOM_CLIENT_ID) -zoomClientSecret=$(ZOOM_CLIENT_SECRET) -zoomRedirectURI=$(ZOOM_OAUTH_REDIRECT_URI)