name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test backend
        run:  cd ./backend/; go test ./... -v

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: cd ./frontend/; npm install

      - name: Build frontend
        run: cd ./frontend/; npx tsc --noEmit && npx parcel build index.tsx
